def main():
    raise Exception("Expected exception")
